name: CI test

on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  - pull_request
  - push
  # Allows you to run this workflow manually from the Actions tab
  - workflow_dispatch

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    env:
      EXTEND_ESLINT: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
